[pytest] #代表pytest配置文件
#配置常用运行参数
addopts = -vs --alluredir=temps --clean-alluredir
#配置测试用例的位置
testpaths = ./testcases
#配置模块名称的规则
python_files = test_*.py
#配置类的规则
python_classes = Test*
#配置测试用例（方法/函数）的规则
python_functions = test_*